"""Build PyANNOW/notebooks/03_pyannow_naml_progression.ipynb — v0.9.0.

Changes vs v0.8.0:
  ISSUE-033/027: calibrated_onset_detect() replaces find_peaks(height=mean)
  ISSUE-028:     Step 7 — RandomForest onset classifier (AppStat Lec 07 / Lab04)
  ISSUE-026:     Ridge diagnostics (VIF, Durbin-Watson, Breusch-Pagan, Lasso CV)
  ISSUE-022:     Descriptive stats + IOI KDE cell (AppStat Lab I)
  ISSUE-023:     PCA biplot (AppStat Lab II)
  ISSUE-024:     t-SNE / UMAP motor-state manifold (AppStat Lab II)
  ISSUE-025:     Four clustering methods comparison (AppStat Lab III/IV)
  ISSUE-041:     F1 precision: .6f display
  ISSUE-030:     Step 0 re-labelled "deterministic body-wave"
  ISSUE-019:     Final chart: F1 panel on LEFT, onset_loss on RIGHT
  ISSUE-042c:    Step 9b (physics-residual MLP) + Step 8c (PINN-Classifier)

Run: python3 PyANNOW/notebooks/_build_naml_progression_nb.py
"""
from __future__ import annotations
import json
from pathlib import Path


def md(*lines) -> dict:
    src = "\n\n".join(s.strip("\n") for s in lines)
    return {"cell_type": "markdown", "metadata": {}, "source": src}


def code(*lines) -> dict:
    src = "\n".join(s.rstrip("\n") for s in lines)
    return {"cell_type": "code", "execution_count": None,
            "metadata": {}, "outputs": [], "source": src}


cells = []

# ── Title ────────────────────────────────────────────────────────────────────
cells += [md(
    "# PyANNOW — NAML Progression  *(v0.9.0)*\n",
    "**Teaching a C. elegans worm to approximate Chopin using only NAML course methods**\n",
    "Each section introduces one new NAML concept and shows the musical improvement it produces.\n",
    "## References\n",
    "- Presentation: `PyANNOW/presentation/index.html` (open in browser)\n"
    "- Living doc: `PyANNOW/docs/PyANNOW_NAML_progression.md`\n"
    "- MIDI target: `shared/examples/chopin_nocturne_op_posth_csharp_minor.mid`\n",
    "## Runtime\n",
    "Approximately **8-12 minutes** end-to-end (Steps 0-9b + visualizations). "
    "Step 8 ODE/PDE PINN (~3-5 min) and Step 8c PINN-Classifier (~5-7 min) are guarded by "
    "`SKIP_PINN=True` / `SKIP_PINN8C=True` — enable only if you want the full PINN story."
)]

# ── 0. Setup ─────────────────────────────────────────────────────────────────
cells += [md("## 0. Setup"), code(
    "import sys, time, warnings\n"
    "warnings.filterwarnings('ignore')\n"
    "\n"
    "import numpy as np\n"
    "import matplotlib.pyplot as plt\n"
    "import matplotlib.gridspec as gridspec\n"
    "import scipy.signal as sps\n"
    "from scipy.io import wavfile\n"
    "from pathlib import Path\n"
    "from IPython.display import Audio, display, Markdown\n"
    "\n"
    "# PyANNOW modules (installed via pip install -e PyANNOW)\n"
    "from pyannow.targets.midi_target import (\n"
    "    parse_midi, note_onsets, onset_loss, piano_roll,\n"
    "    musical_f1, ioi_similarity, calibrated_onset_detect)\n"
    "from pyannow.composer.piano_synth import synthesise_melody\n"
    "from pyannow.composer.worm_optimizer_fast import (\n"
    "    run_forward_fast, onsets_from_result, MUSCLE_PITCHES_96)\n"
    "from pyannow.composer.worm_optimizer import generate_neural_activity_302\n"
    "from pyannow.ion_channels.celegans_hh import DEFAULT_PARAMS\n"
    "\n"
    "from pyannow.step1_svd.encoder      import rsvd, neural_scores, choose_k_by_variance\n"
    "from pyannow.step1_svd.procrustes   import procrustes_align, build_chopin_features\n"
    "from pyannow.step2_clustering.motor_primitives import (\n"
    "    pca_reduce, find_motor_primitives, cluster_to_notes, choose_k_silhouette)\n"
    "from pyannow.step3_regression.ridge_composer import RidgeComposer, explained_variance_by_ridge\n"
    "from pyannow.step4_ffnn.jax_composer import create_model, init_params, model_summary\n"
    "from pyannow.step5_training.adam_trainer import train_adam\n"
    "from pyannow.step6_lbfgs.lbfgs_polish import polish_lbfgs\n"
    "from pyannow.step8_pinn.locomotion_pinn import compare_ode_vs_pde\n"
    "\n"
    "plt.rcParams.update({'figure.figsize': (11, 4), 'axes.grid': True, 'grid.alpha': 0.3})\n"
    "OUTDIR = Path('step_outputs'); OUTDIR.mkdir(exist_ok=True)\n"
    "MIDI_PATH = Path('../../shared/examples/chopin_nocturne_op_posth_csharp_minor.mid')\n"
    "DURATION = 10.0   # seconds to simulate and compare\n"
    "SKIP_PINN = True  # set False to run Step 8 ODE/PDE PINN (~3-5 min extra)\n"
    "rng = np.random.default_rng(0)\n"
    "print('PyANNOW v0.9.0 loaded ✓')\n"
    "print(f'SKIP_PINN={SKIP_PINN}  (set True to skip the 3-5 min PINN step)')"
)]

# ── Global data generation ────────────────────────────────────────────────────
cells += [md(
    "## Data preparation\n",
    "Generate the worm's neural activity and load the Chopin target.\n",
    "**Worm:** run the 96-cell Boyle et al. (2012) 4×24 forward model to get `V_muscles` "
    "(96 muscle cells × T timesteps across 4 quadrants: DL/VL/DR/VR).  \n"
    "**Neural activity (v0.7.0):** `generate_neural_activity_302()` produces a biologically-structured "
    "302-neuron matrix with **k ≥ 4 independent principal components** (command interneurons, "
    "A/B/D motor neurons, interneurons, sensory neurons).  \n"
    "**Chopin:** parsed from the MIDI file into note-onset times.\n",
    "**v0.9.0:** `calibrated_onset_detect()` replaces `find_peaks(height=mean)` for Steps 1, 3, 4-6 "
    "(ISSUE-033): logistic regression on peak heights + Youden's J threshold selection."
), code(
    "# ── 1. Run 96-cell Boyle forward model (v0.7.0 default) ─────────────────\n"
    "result_worm = run_forward_fast(\n"
    "    DEFAULT_PARAMS, duration_s=DURATION, dt_ms=0.5,\n"
    "    drive_freq_hz=1.5, drive_amplitude=12.0, random_seed=42)\n"
    "V_mus  = result_worm['V_muscles']           # (T, 96)  muscle voltages\n"
    "t_ms   = result_worm['t_arr_ms']            # (T,)  time in ms\n"
    "t_arr  = t_ms * 1e-3                        # (T,)  time in seconds\n"
    "worm_events = result_worm['note_onsets_s']  # rule-based baseline\n"
    "n_muscles   = result_worm['n_muscles']      # 96 (Boyle 4×24)\n"
    "T_pts       = len(t_arr)\n"
    "print(f'Worm simulation: {n_muscles}-cell model, T={T_pts} timesteps, '\n"
    "      f'{len(worm_events)} note events')\n"
    "print(f'Quadrant pitch ranges: DL=MIDI 24-47, VL=48-71, DR=72-95, VR=96-119')\n"
    "\n"
    "# ── 2. Biologically-structured 302-neuron activity (v0.7.0) ─────────────\n"
    "X_neural = generate_neural_activity_302(\n"
    "    n_steps=T_pts, dt_ms=0.5, drive_freq_hz=1.5, seed=42)\n"
    "s_check = np.linalg.svd(X_neural, compute_uv=False)\n"
    "n_sig = int((s_check > s_check[0] * 0.1).sum())\n"
    "print(f'Neural activity: {X_neural.shape}  |  Significant PCs: {n_sig}  '\n"
    "      f'(v0.6.0 had k=1 — NAML steps could not beat Step 0)')\n"
    "\n"
    "# ── 3. Load Chopin MIDI ───────────────────────────────────────────────────\n"
    "events_chopin, bpm = parse_midi(MIDI_PATH)\n"
    "t_on_chopin = note_onsets(events_chopin)\n"
    "print(f'Chopin: {len(events_chopin)} notes, {bpm:.0f} BPM, {t_on_chopin.max():.0f}s total')\n"
    "\n"
    "# Build Chopin feature matrix — v0.8.0: auto-select k by 90% variance rule (ISSUE-034)\n"
    "from pyannow.step1_svd.procrustes import chopin_cumvar\n"
    "cv_chopin = chopin_cumvar(events_chopin, duration_s=DURATION)\n"
    "C_chopin = build_chopin_features(events_chopin, duration_s=DURATION, n_bins=T_pts,\n"
    "                                  k_chopin=None, var_threshold=0.90)\n"
    "k_chopin = C_chopin.shape[1]\n"
    "print(f'Chopin feature matrix: {C_chopin.shape}  (T × k_chopin={k_chopin})')\n"
    "\n"
    "# Metric accumulators\n"
    "losses    = {}   # onset_loss per step\n"
    "f1_scores = {}   # musical_f1 per step (primary — cannot be gamed by sparsity)\n"
    "ioi_sims  = {}   # IOI histogram intersection per step"
)]

# ── AppStat Lab I: Descriptive stats + IOI KDE (ISSUE-022) ───────────────────
cells += [md(
    "## AppStat Lab I — Descriptive statistics of worm and Chopin onset distributions\n",
    "Before any learning: compare the basic statistical properties of worm vs Chopin onsets.  \n"
    "**IOI (inter-onset interval)** is the key rhythmic fingerprint. The worm's IOI peaks at "
    "the body-wave period; Chopin's is broad and musically structured.  \n"
    "This is the quantitative basis for the metric comparison in ISSUE-016.",
    "*(AppStat Lab I: kurtosis, skewness, KDE — Lab01 descriptive tools)*"
), code(
    "# AppStat Lab I: descriptive stats of onset distributions (ISSUE-022)\n"
    "from scipy.stats import kurtosis as kurt, skew, gaussian_kde\n"
    "import pandas as pd\n"
    "\n"
    "onsets_base = onsets_from_result(result_worm)\n"
    "t_on_win = t_on_chopin[t_on_chopin <= DURATION]\n"
    "\n"
    "def ioi_stats(onsets, label):\n"
    "    o = np.sort(onsets[onsets <= DURATION])\n"
    "    ioi = np.diff(o) if len(o) > 1 else np.array([])\n"
    "    if len(ioi) == 0:\n"
    "        return {'label': label, 'n': len(o), 'ioi_mean': np.nan,\n"
    "                'ioi_std': np.nan, 'ioi_skew': np.nan, 'ioi_kurt': np.nan}\n"
    "    return {'label': label, 'n': len(o),\n"
    "            'ioi_mean': ioi.mean(), 'ioi_std': ioi.std(ddof=1),\n"
    "            'ioi_skew': float(skew(ioi)), 'ioi_kurt': float(kurt(ioi))}\n"
    "\n"
    "df_stats = pd.DataFrame([\n"
    "    ioi_stats(onsets_base, 'Worm Step 0 (body-wave)'),\n"
    "    ioi_stats(t_on_chopin, 'Chopin (Nocturne C# minor)'),\n"
    "])\n"
    "print('Descriptive stats — inter-onset intervals:')\n"
    "print(df_stats.to_string(index=False))\n"
    "\n"
    "# IOI KDE plot\n"
    "fig, ax = plt.subplots(figsize=(9, 3))\n"
    "bins = np.linspace(0, 2.0, 200)\n"
    "for onsets, label, color in [\n"
    "    (onsets_base, 'Worm Step 0 (body-wave)', 'steelblue'),\n"
    "    (t_on_chopin, 'Chopin', 'crimson')]:\n"
    "    ioi = np.diff(np.sort(onsets[onsets <= DURATION]))\n"
    "    if len(ioi) > 1:\n"
    "        kde = gaussian_kde(ioi, bw_method=0.15)\n"
    "        ax.plot(bins, kde(bins), lw=2, label=label, color=color)\n"
    "        ax.axvline(ioi.mean(), ls='--', color=color, alpha=0.5, lw=1)\n"
    "ax.set(xlabel='IOI (s)', ylabel='density', title='IOI distributions — worm vs Chopin')\n"
    "ax.legend(); plt.tight_layout()\n"
    "plt.savefig(OUTDIR/'appstat_lab1_ioi_kde.png', dpi=100); plt.show()\n"
    "print('Worm IOI is periodic (single spike at body-wave period);'\n"
    "      ' Chopin is broad and musically varied — NAML must bridge this gap.')"
)]

# ── Step 0 ────────────────────────────────────────────────────────────────────
cells += [md(
    "## Step 0 — Deterministic body-wave baseline (no learning)\n",
    "**ISSUE-030 (v0.9.0):** Step 0 is NOT random — it runs the deterministic "
    "Boyle 4×24 forward model with fixed `drive_freq_hz=1.5, random_seed=42`.  \n"
    "Its IOI distribution peaks sharply at the body-wave period (~0.67 s).  \n"
    "Only the pitch/Chopin timing alignment is unlearned — not the temporal structure.  \n"
    "**NAML used:** none.  **Goal:** every subsequent step must beat this F1."
), code(
    "# Step 0: deterministic body-wave baseline (ISSUE-030 fix: not 'random')\n"
    "L_base  = onset_loss(onsets_base, t_on_chopin, window_s=DURATION)\n"
    "F1_base = musical_f1(onsets_base, t_on_chopin, window_s=DURATION)\n"
    "I_base  = ioi_similarity(onsets_base, t_on_chopin, window_s=DURATION)\n"
    "print(f'Step 0 (body-wave baseline): {len(onsets_base)} notes  '\n"
    "      f'loss={L_base:.5f}  F1={F1_base[\"f1\"]:.6f}  IOI={I_base:.3f}')\n"
    "print(f'  precision={F1_base[\"precision\"]:.3f}  recall={F1_base[\"recall\"]:.3f}  '\n"
    "      f'tp_worm={F1_base[\"tp_worm\"]}  tp_chopin={F1_base[\"tp_chopin\"]}')\n"
    "\n"
    "audio_base, fs = synthesise_melody(worm_events, duration_s=DURATION)\n"
    "print('Step 0 — body-wave melody:')\n"
    "display(Audio(audio_base, rate=fs, autoplay=False))\n"
    "\n"
    "wavfile.write(str(OUTDIR/'step0_baseline.wav'), fs, (audio_base*28000).astype('int16'))\n"
    "losses['Step 0 (body-wave)']    = L_base\n"
    "f1_scores['Step 0 (body-wave)'] = F1_base['f1']\n"
    "ioi_sims['Step 0 (body-wave)']  = I_base"
)]

# ── Step 1a: SVD ──────────────────────────────────────────────────────────────
cells += [md(
    "## Step 1a — SVD encoder (NAML L06 / Lab01)\n",
    "**Eckart-Young theorem:** the best rank-`k` approximation of the 302-neuron activity "
    "matrix is the truncated SVD.\n",
    "$$X_k = U_k \\Sigma_k V_k^T$$\n",
    "We use **Randomized SVD** (from the course's own `rsvd_2024.ipynb`) to compress "
    "302 dimensions → k=4 principal neural components.\n",
    "Lab01 analogy: just as we compressed the Mondrian painting with SVD, "
    "here we compress the worm's neural activity."
), code(
    "# Step 1a: RSVD (Lab01 / L06)\n"
    "k_worm = choose_k_by_variance(X_neural, variance_threshold=0.90)\n"
    "k_worm = min(k_worm, 4)  # cap at 4 for speed\n"
    "print(f'Chosen k = {k_worm} (explains ≥90% variance)')\n"
    "\n"
    "U_k, s_k, Vt_k = rsvd(X_neural, k=k_worm, q=1, seed=0)\n"
    "Z_worm = neural_scores(X_neural, U_k).T  # (T, k_worm)\n"
    "\n"
    "# Scree plot (Lab01 analogy)\n"
    "s_full = np.linalg.svd(X_neural, compute_uv=False)\n"
    "cum_var = np.cumsum(s_full**2) / (s_full**2).sum()\n"
    "\n"
    "fig, ax = plt.subplots(1, 2, figsize=(10, 3))\n"
    "ax[0].semilogy(s_full[:20], 'k-o', ms=4); ax[0].axvline(k_worm-1, color='red', ls='--')\n"
    "ax[0].set(xlabel='component', ylabel='σ', title='Singular values (scree plot)')\n"
    "ax[1].plot(cum_var[:20]*100, 'b-o', ms=4); ax[1].axhline(90, color='red', ls='--')\n"
    "ax[1].set(xlabel='k', ylabel='% variance', title=f'Cumulative variance (k={k_worm} → 90%)')\n"
    "plt.tight_layout(); plt.savefig(OUTDIR/'step1a_svd.png', dpi=100); plt.show()\n"
    "print(f'Z_worm shape: {Z_worm.shape}  (302-D → {k_worm}-D)')"
)]

# ── AppStat Lab II: PCA biplot (ISSUE-023) ────────────────────────────────────
cells += [md(
    "## AppStat Lab II — PCA biplot of worm neural subspace\n",
    "**Biplot** (AppStat Lab II): scores scatter + loading arrows — shows *which neurons* "
    "drive PC1 vs PC2.  \n"
    "Each point is a 0.5 ms timestep; arrows are the top-magnitude neuron loadings.  \n"
    "The block structure (7 neuron groups in `generate_neural_activity_302`) should appear "
    "as distinct clusters of loading arrows pointing in different directions.",
    "*(AppStat Lab II: PCA, biplot, loadings)*"
), code(
    "# AppStat Lab II: PCA biplot (ISSUE-023)\n"
    "from sklearn.preprocessing import StandardScaler\n"
    "from sklearn.decomposition import PCA\n"
    "\n"
    "Xs = StandardScaler().fit_transform(X_neural.T)  # (T, 302) standardized\n"
    "pca_bio = PCA(n_components=2, random_state=0).fit(Xs)\n"
    "Z_bio2  = pca_bio.transform(Xs)  # (T, 2) scores\n"
    "loadings = pca_bio.components_.T  # (302, 2)\n"
    "\n"
    "# Biplot\n"
    "fig, ax = plt.subplots(figsize=(7, 6))\n"
    "ax.scatter(Z_bio2[:, 0], Z_bio2[:, 1], s=2, alpha=0.2, c='steelblue', label='timesteps')\n"
    "\n"
    "# Top-15 loadings by L2 magnitude\n"
    "arrow_scale = 3.0 * np.abs(Z_bio2).max()\n"
    "mags = np.linalg.norm(loadings, axis=1)\n"
    "top_idx = np.argsort(mags)[-15:]\n"
    "for i in top_idx:\n"
    "    ax.annotate('', xy=(loadings[i, 0]*arrow_scale, loadings[i, 1]*arrow_scale),\n"
    "                xytext=(0, 0),\n"
    "                arrowprops=dict(arrowstyle='->', color='crimson', lw=1.2, alpha=0.7))\n"
    "    ax.text(loadings[i, 0]*arrow_scale*1.05, loadings[i, 1]*arrow_scale*1.05,\n"
    "            f'n{i}', fontsize=7, color='crimson')\n"
    "\n"
    "ax.set(xlabel=f'PC1 ({pca_bio.explained_variance_ratio_[0]*100:.1f}%)',\n"
    "       ylabel=f'PC2 ({pca_bio.explained_variance_ratio_[1]*100:.1f}%)',\n"
    "       title='PCA biplot — 302-neuron activity (Lab II)')\n"
    "ax.legend(fontsize=8); plt.tight_layout()\n"
    "plt.savefig(OUTDIR/'appstat_lab2_biplot.png', dpi=100); plt.show()\n"
    "print(f'PC1+PC2 explain {pca_bio.explained_variance_ratio_.sum()*100:.1f}% of neural variance')"
)]

# ── Step 1b: Procrustes ───────────────────────────────────────────────────────
cells += [md(
    "## Step 1b — Procrustes alignment (NAML L06/L09)\n",
    "**Orthogonal Procrustes problem:** find the rotation `R` that aligns "
    "the worm's k-dim subspace to Chopin's k-dim subspace.\n",
    "$$R = \\arg\\min_{R^TR=I} \\|W_k R - C_k\\|_F^2 "
    "\\quad\\Rightarrow\\quad C_k^T W_k = U \\Sigma V^T,\\; R = VU^T$$\n",
    "v0.8.0: Procrustes standardizes `W_k` column-wise (ISSUE-032) — prevents PC1 dominating.  \n"
    "v0.9.0: onset detection uses **calibrated logistic classifier** (ISSUE-033) instead of "
    "magic `height=activ.mean()` threshold."
), code(
    "# Step 1b: Procrustes (L06/L09) — calibrated onset detection (ISSUE-033)\n"
    "result_proc = procrustes_align(Z_worm, C_chopin, standardize=True)\n"
    "R = result_proc['R']\n"
    "Z_aligned = result_proc['W_k_scaled'] @ R\n"
    "print(f'Alignment residual (v0.8.0 standardized): {result_proc[\"residual\"]:.4f}')\n"
    "\n"
    "# v0.9.0: calibrated onset detector (ISSUE-033)\n"
    "activ_proc  = np.abs(Z_aligned).max(axis=1)\n"
    "onsets_proc = calibrated_onset_detect(\n"
    "    activ_proc, t_on_chopin, t_arr, tol_s=0.05, refractory_s=0.28)\n"
    "L_proc  = onset_loss(onsets_proc, t_on_chopin, window_s=DURATION)\n"
    "F1_proc = musical_f1(onsets_proc, t_on_chopin, window_s=DURATION)\n"
    "I_proc  = ioi_similarity(onsets_proc, t_on_chopin, window_s=DURATION)\n"
    "print(f'Step 1 (SVD+Procrustes): {len(onsets_proc)} notes  '\n"
    "      f'loss={L_proc:.5f}  F1={F1_proc[\"f1\"]:.6f}  IOI={I_proc:.3f}')\n"
    "print(f'  beats Step 0 F1? {\"YES ✓\" if F1_proc[\"f1\"] > f1_scores[\"Step 0 (body-wave)\"] else \"NO\"}')\n"
    "losses['Step 1 (SVD+Procrustes)']    = L_proc\n"
    "f1_scores['Step 1 (SVD+Procrustes)'] = F1_proc['f1']\n"
    "ioi_sims['Step 1 (SVD+Procrustes)']  = I_proc"
)]

# ── Step 2: K-means ───────────────────────────────────────────────────────────
cells += [md(
    "## Step 2 — PCA + K-means motor primitives (NAML L08/L10 / Lab02)\n",
    "**PCA** reduces the neural trajectory to 2-4 principal directions — the worm's "
    "'motor state space'. **K-means** clusters these into discrete motor primitives "
    "(Forward / Backward / Turn / Pause).\n",
    "**Lab02 analogy:** same as clustering MNIST digit images — here we cluster "
    "worm neural states. Each cluster transition = one musical note."
), code(
    "# Step 2: PCA + K-means (L08/L10 / Lab02)\n"
    "scores, pca_obj = pca_reduce(X_neural, n_components=4, standardize=True)\n"
    "print(f'PCA explained variance: {pca_obj.explained_variance_ratio_.round(3)}')\n"
    "\n"
    "sil_res = choose_k_silhouette(scores, k_range=range(2, 7))\n"
    "k_clust = sil_res['best_k']\n"
    "print(f'Best k by silhouette: {k_clust}  (scores: {sil_res[\"scores\"]})')\n"
    "\n"
    "labels, km_obj = find_motor_primitives(scores, k=k_clust)\n"
    "cluster_names  = ['Forward', 'Backward', 'Turn', 'Pause'][:k_clust]\n"
    "\n"
    "fig, ax = plt.subplots(figsize=(6, 5))\n"
    "for cl in range(k_clust):\n"
    "    mask = labels == cl\n"
    "    ax.scatter(scores[mask, 0], scores[mask, 1], s=6, alpha=0.5,\n"
    "               label=cluster_names[cl] if cl < len(cluster_names) else f'Cluster {cl}')\n"
    "ax.set(xlabel='PC1', ylabel='PC2', title='Worm motor states in PCA space')\n"
    "ax.legend(); plt.tight_layout()\n"
    "plt.savefig(OUTDIR/'step2_clusters.png', dpi=100); plt.show()\n"
    "\n"
    "onsets_clust = np.array([e[0] for e in\n"
    "    cluster_to_notes(labels, t_ms, min_interval_ms=280)])\n"
    "L_clust  = onset_loss(onsets_clust, t_on_chopin, window_s=DURATION)\n"
    "F1_clust = musical_f1(onsets_clust, t_on_chopin, window_s=DURATION)\n"
    "I_clust  = ioi_similarity(onsets_clust, t_on_chopin, window_s=DURATION)\n"
    "print(f'Step 2 (K-means):       {len(onsets_clust)} notes  '\n"
    "      f'loss={L_clust:.5f}  F1={F1_clust[\"f1\"]:.6f}  IOI={I_clust:.3f}')\n"
    "print(f'  beats Step 0 F1? {\"YES ✓\" if F1_clust[\"f1\"] > f1_scores[\"Step 0 (body-wave)\"] else \"NO\"}')\n"
    "losses['Step 2 (K-means)']    = L_clust\n"
    "f1_scores['Step 2 (K-means)'] = F1_clust['f1']\n"
    "ioi_sims['Step 2 (K-means)']  = I_clust"
)]

# ── AppStat Lab II: t-SNE / UMAP (ISSUE-024) ─────────────────────────────────
cells += [md(
    "## AppStat Lab II — t-SNE / UMAP motor-state manifold\n",
    "PCA is linear; the worm's neural manifold may not be.  \n"
    "**t-SNE** (AppStat Lab II, `TSNE(perplexity=30, init='pca')`) and "
    "**UMAP** (`UMAP(n_neighbors=15, min_dist=0.1)`) give nonlinear projections.  \n"
    "Colouring by K-means label shows whether the clusters correspond to real "
    "manifold structure or to arbitrary partitions.  \n"
    "**t-SNE caveat:** inter-cluster distances and cluster sizes are NOT meaningful — "
    "UMAP preserves more global structure.",
    "*(AppStat Lab II: t-SNE, UMAP, non-linear dim reduction)*"
), code(
    "# AppStat Lab II: t-SNE / UMAP (ISSUE-024)\n"
    "from sklearn.manifold import TSNE\n"
    "try:\n"
    "    import umap\n"
    "    _umap_ok = True\n"
    "except ImportError:\n"
    "    _umap_ok = False\n"
    "    print('umap-learn not installed — skipping UMAP (pip install umap-learn)')\n"
    "\n"
    "Xs_2d = StandardScaler().fit_transform(X_neural.T)  # (T, 302)\n"
    "# Subsample for speed (t-SNE is O(T^2))\n"
    "sub = min(2000, T_pts)\n"
    "idx_sub = np.linspace(0, T_pts-1, sub, dtype=int)\n"
    "Xs_sub  = Xs_2d[idx_sub]\n"
    "lab_sub = labels[idx_sub]\n"
    "\n"
    "Y_tsne = TSNE(n_components=2, perplexity=30, init='pca', random_state=0).fit_transform(Xs_sub)\n"
    "\n"
    "n_cols = 2 if _umap_ok else 1\n"
    "fig, axes = plt.subplots(1, n_cols, figsize=(6*n_cols, 5))\n"
    "if n_cols == 1: axes = [axes]\n"
    "\n"
    "axes[0].scatter(Y_tsne[:, 0], Y_tsne[:, 1], c=lab_sub, cmap='tab10', s=6, alpha=0.7)\n"
    "axes[0].set(title=f't-SNE (perp=30) — coloured by Step 2 K-means label')\n"
    "\n"
    "if _umap_ok:\n"
    "    Y_umap = umap.UMAP(n_neighbors=15, min_dist=0.1, random_state=0).fit_transform(Xs_sub)\n"
    "    axes[1].scatter(Y_umap[:, 0], Y_umap[:, 1], c=lab_sub, cmap='tab10', s=6, alpha=0.7)\n"
    "    axes[1].set(title='UMAP (n_neighbors=15) — coloured by K-means label')\n"
    "\n"
    "plt.suptitle('Non-linear dim reduction of worm motor states (Lab II)', fontsize=11)\n"
    "plt.tight_layout(); plt.savefig(OUTDIR/'appstat_lab2_manifold.png', dpi=100); plt.show()"
)]

# ── AppStat Lab III/IV: 4-method clustering comparison (ISSUE-025) ────────────
cells += [md(
    "## AppStat Lab III/IV — Four clustering methods on motor primitives\n",
    "AppStat 2026 Lab III + IV teaches four canonical clustering methods.  \n"
    "Step 2 only used K-means — here we compare all four on the same PCA scores "
    "and report silhouette + adjusted Rand index between methods.  \n"
    "- **K-means** (Lab III): spherical clusters, hard assignment, fixed k\n"
    "- **Ward** (Lab III): hierarchical, dendrogram, cophenetic coefficient\n"
    "- **DBSCAN** (Lab IV): density-based, noise as `-1`, no k required\n"
    "- **GMM** (Lab IV): probabilistic, BIC-selected, soft assignment",
    "*(AppStat Lab III: linkage, dendrogram, cophenet | Lab IV: DBSCAN, GMM, BIC)*"
), code(
    "# AppStat Lab III/IV: 4-method clustering comparison (ISSUE-025)\n"
    "from sklearn.cluster import DBSCAN, KMeans\n"
    "from sklearn.mixture import GaussianMixture\n"
    "from sklearn.metrics import adjusted_rand_score, silhouette_score\n"
    "from scipy.cluster.hierarchy import cophenet, fcluster, linkage, dendrogram\n"
    "from scipy.spatial.distance import pdist\n"
    "\n"
    "# Subsample for speed — Ward linkage is O(n²), slow on 20000 pts\n"
    "sub_c = min(2000, T_pts)\n"
    "idx_c = np.linspace(0, T_pts-1, sub_c, dtype=int)\n"
    "sc2   = scores[idx_c, :2]      # (sub_c, 2) subsampled PCA scores\n"
    "lab_c = labels[idx_c]          # matching K-means labels\n"
    "print(f'Clustering on {sub_c} subsampled points (full T={T_pts})')\n"
    "\n"
    "# K-means (refit on subsample for fair comparison)\n"
    "from sklearn.cluster import KMeans as _KM\n"
    "labels_km = _KM(n_clusters=k_clust, random_state=0, n_init=10).fit_predict(sc2)\n"
    "sil_km    = silhouette_score(sc2, labels_km)\n"
    "\n"
    "# Ward hierarchical\n"
    "Z_ward = linkage(sc2, method='ward')\n"
    "c_corr, _ = cophenet(Z_ward, pdist(sc2))\n"
    "labels_ward = fcluster(Z_ward, t=k_clust, criterion='maxclust') - 1\n"
    "sil_ward    = silhouette_score(sc2, labels_ward)\n"
    "\n"
    "# DBSCAN (eps chosen by NearestNeighbors elbow)\n"
    "from sklearn.neighbors import NearestNeighbors\n"
    "nn = NearestNeighbors(n_neighbors=5).fit(sc2)\n"
    "dists, _ = nn.kneighbors(sc2)\n"
    "eps_auto = float(np.percentile(dists[:, -1], 90))\n"
    "labels_db = DBSCAN(eps=eps_auto, min_samples=5).fit_predict(sc2)\n"
    "sil_db = silhouette_score(sc2, labels_db) if len(np.unique(labels_db)) > 1 else np.nan\n"
    "\n"
    "# GMM (BIC selection)\n"
    "bic_k = {k: GaussianMixture(n_components=k, random_state=0).fit(sc2).bic(sc2)\n"
    "         for k in range(2, 7)}\n"
    "k_gmm     = min(bic_k, key=bic_k.get)\n"
    "gmm       = GaussianMixture(n_components=k_gmm, random_state=0).fit(sc2)\n"
    "labels_gmm = gmm.predict(sc2)\n"
    "sil_gmm   = silhouette_score(sc2, labels_gmm)\n"
    "\n"
    "print(f'\\nClustering comparison (silhouette score, higher = more compact clusters):')\n"
    "print(f'  K-means  (k={k_clust}):             sil={sil_km:.3f}')\n"
    "print(f'  Ward     (k={k_clust}):             sil={sil_ward:.3f}  cophenetic={c_corr:.3f}')\n"
    "print(f'  DBSCAN   (eps={eps_auto:.3f}):      sil={sil_db:.3f}  (noise={np.sum(labels_db==-1)})')\n"
    "print(f'  GMM      (BIC→k={k_gmm}):           sil={sil_gmm:.3f}')\n"
    "\n"
    "# ARI pairwise\n"
    "import itertools\n"
    "lbl_map = {'KMeans': labels_km, 'Ward': labels_ward, 'GMM': labels_gmm}\n"
    "print('\\nPairwise ARI:')\n"
    "for a, b in itertools.combinations(lbl_map, 2):\n"
    "    print(f'  {a} vs {b}: {adjusted_rand_score(lbl_map[a], lbl_map[b]):.3f}')\n"
    "\n"
    "# 2×2 scatter + dendrogram\n"
    "fig, axes = plt.subplots(2, 2, figsize=(11, 9))\n"
    "for ax, (lbl, name) in zip(axes.flat[:3], [\n"
    "    (labels_km, f'K-means (k={k_clust}, sil={sil_km:.2f})'),\n"
    "    (labels_ward, f'Ward (k={k_clust}, sil={sil_ward:.2f}, cophen={c_corr:.2f})'),\n"
    "    (labels_gmm, f'GMM BIC (k={k_gmm}, sil={sil_gmm:.2f})'),\n"
    "]):\n"
    "    ax.scatter(sc2[:, 0], sc2[:, 1], c=lbl, cmap='tab10', s=4, alpha=0.5)\n"
    "    ax.set(title=name, xlabel='PC1', ylabel='PC2')\n"
    "dendrogram(Z_ward, ax=axes[1,1], p=5, truncate_mode='level', no_labels=True)\n"
    "axes[1,1].set(title=f'Ward dendrogram (cophenetic={c_corr:.3f})')\n"
    "plt.suptitle('Four clustering methods on worm motor states (Lab III/IV)', fontsize=11)\n"
    "plt.tight_layout(); plt.savefig(OUTDIR/'appstat_lab34_clustering.png', dpi=100); plt.show()"
)]

# ── Step 3: Ridge ─────────────────────────────────────────────────────────────
cells += [md(
    "## Step 3 — Ridge regression composer (NAML L07/L11 / Lab07)\n",
    "**Ridge regression** learns a regularised linear mapping\n",
    "$$W = (Z^T Z + \\lambda I)^{-1} Z^T C$$\n",
    "from the worm's neural PCA scores `Z` to the Chopin musical features `C`.  \n"
    "v0.9.0 adds **Lab V diagnostics** (ISSUE-026): VIF, Durbin-Watson, "
    "Breusch-Pagan, and Lasso CV to check whether Ridge over-specifies the feature space.  \n"
    "v0.9.0 onset detection: calibrated logistic classifier (ISSUE-033).",
    "**Lab07 analogy:** same as predicting California housing prices from features."
), code(
    "# Step 3: Ridge + Lab V diagnostics (ISSUE-026) + calibrated onset (ISSUE-033)\n"
    "import statsmodels.api as sm\n"
    "from statsmodels.stats.diagnostic import het_breuschpagan\n"
    "from statsmodels.stats.outliers_influence import variance_inflation_factor\n"
    "from statsmodels.stats.stattools import durbin_watson\n"
    "from sklearn.linear_model import LassoCV\n"
    "\n"
    "rc = RidgeComposer(alpha=None)  # CV selects λ\n"
    "rc.fit(Z_worm, C_chopin)\n"
    "print(f'Best α (RidgeCV): {rc.alpha_:.4f}')\n"
    "\n"
    "# ── Lab V diagnostics ────────────────────────────────────────────────────\n"
    "C_pred_ridge = rc.predict(Z_worm)\n"
    "resid = C_chopin - C_pred_ridge  # (T, k_chopin)\n"
    "resid0 = resid[:, 0]             # first Chopin feature dimension\n"
    "\n"
    "# VIF — multicollinearity of the worm PCs as predictors\n"
    "Xc = sm.add_constant(Z_worm)\n"
    "vif = [variance_inflation_factor(Xc, i+1) for i in range(k_worm)]\n"
    "print(f'\\nLab V VIF per worm PC: {[f\"{v:.2f}\" for v in vif]}')\n"
    "print(f'  (VIF > 5 → multicollinearity concern)')\n"
    "\n"
    "# Durbin-Watson — residual autocorrelation\n"
    "dw = durbin_watson(resid0)\n"
    "print(f'Durbin-Watson: {dw:.3f}  (2.0 = no autocorr; <1.5 = positive autocorr)')\n"
    "\n"
    "# Breusch-Pagan — heteroskedasticity\n"
    "ols_fit = sm.OLS(resid0, Xc).fit()\n"
    "bp_lm, bp_p, _, _ = het_breuschpagan(ols_fit.resid, ols_fit.model.exog)\n"
    "print(f'Breusch-Pagan: LM={bp_lm:.3f}  p={bp_p:.4f}  '\n"
    "      f'({\"heteroskedastic\" if bp_p < 0.05 else \"homoskedastic\"})')\n"
    "\n"
    "# Lasso CV — true effective dimensionality\n"
    "lasso = LassoCV(cv=5, random_state=0, max_iter=2000).fit(Z_worm, C_chopin[:, 0])\n"
    "n_nonzero = int((np.abs(lasso.coef_) > 1e-6).sum())\n"
    "print(f'LassoCV α={lasso.alpha_:.4f} — {n_nonzero}/{k_worm} PCs non-zero '\n"
    "      f'(true effective dim = {n_nonzero})')\n"
    "\n"
    "# Ridge R² curve\n"
    "lam_res = explained_variance_by_ridge(Z_worm, C_chopin)\n"
    "fig, ax = plt.subplots(figsize=(6, 3))\n"
    "ax.semilogx(lam_res['alphas'], lam_res['r2s'], 'b-o', ms=4, lw=1.5)\n"
    "ax.axvline(lam_res['best_alpha'], color='red', ls='--',\n"
    "           label=f'best α={lam_res[\"best_alpha\"]:.3f}')\n"
    "ax.set(xlabel='λ (regularisation)', ylabel='R²', title='Ridge: R² vs λ')\n"
    "ax.legend(); plt.tight_layout()\n"
    "plt.savefig(OUTDIR/'step3_ridge.png', dpi=100); plt.show()\n"
    "\n"
    "# v0.9.0: calibrated onset detector\n"
    "activ_ridge  = np.abs(C_pred_ridge).max(axis=1)\n"
    "onsets_ridge = calibrated_onset_detect(\n"
    "    activ_ridge, t_on_chopin, t_arr, tol_s=0.05, refractory_s=0.28)\n"
    "L_ridge  = onset_loss(onsets_ridge, t_on_chopin, window_s=DURATION)\n"
    "F1_ridge = musical_f1(onsets_ridge, t_on_chopin, window_s=DURATION)\n"
    "I_ridge  = ioi_similarity(onsets_ridge, t_on_chopin, window_s=DURATION)\n"
    "ev_ridge = rc.evaluate(Z_worm, C_chopin)\n"
    "print(f'\\nStep 3 (Ridge): {len(onsets_ridge)} notes  '\n"
    "      f'loss={L_ridge:.5f}  F1={F1_ridge[\"f1\"]:.6f}  IOI={I_ridge:.3f}  R²={ev_ridge[\"r2\"]:.3f}')\n"
    "print(f'  beats Step 0 F1? {\"YES ✓\" if F1_ridge[\"f1\"] > f1_scores[\"Step 0 (body-wave)\"] else \"NO\"}')\n"
    "losses['Step 3 (Ridge)']    = L_ridge\n"
    "f1_scores['Step 3 (Ridge)'] = F1_ridge['f1']\n"
    "ioi_sims['Step 3 (Ridge)']  = I_ridge"
)]

# ── Step 4+5+6: MLP + Adam + L-BFGS ─────────────────────────────────────────
cells += [md(
    "## Steps 4-6 — MLP + Adam + L-BFGS (NAML L14-22 / Labs 06/08/10)\n",
    "Three NAML concepts combined:\n",
    "- **Step 4 (L14-17 / Lab06):** replace the linear ridge map with a 2-layer "
    "MLP. Xavier init, tanh activations, autodiff via `jax.grad`.\n"
    "- **Step 5 (L20 / Lab10):** train with mini-batch Adam. Per-parameter LR "
    "adapts to the neural feature scale mismatch.\n"
    "- **Step 6 (L22 / Lab08):** L-BFGS second-stage polish — super-linear "
    "convergence squeezes the last 5-10% loss that Adam plateaued on.\n",
    "v0.9.0: onset detection uses calibrated logistic classifier (ISSUE-033)."
), code(
    "# Steps 4-6: MLP + Adam + L-BFGS + calibrated onset (ISSUE-033)\n"
    "import jax, jax.numpy as jnp\n"
    "\n"
    "model   = create_model(k_worm=k_worm, k_chopin=k_chopin, hidden=32, depth=2)\n"
    "params  = init_params(model, k_worm)\n"
    "print(model_summary(model, k_worm))\n"
    "\n"
    "print('\\nStep 5 — Adam training...')\n"
    "params, h_adam = train_adam(\n"
    "    model, params, Z_worm, C_chopin,\n"
    "    lr=1e-3, epochs=300, batch_sz=32, verbose=True)\n"
    "\n"
    "print('\\nStep 6 — L-BFGS polish...')\n"
    "params, h_lbfgs = polish_lbfgs(\n"
    "    model, params, Z_worm, C_chopin, max_steps=60, verbose=True)\n"
    "\n"
    "from pyannow.step4_ffnn.jax_composer import predict as jax_predict\n"
    "C_pred_mlp = jax_predict(params, model, Z_worm)\n"
    "activ_mlp  = np.abs(C_pred_mlp).max(axis=1)\n"
    "\n"
    "# v0.9.0: calibrated onset detector\n"
    "onsets_mlp = calibrated_onset_detect(\n"
    "    activ_mlp, t_on_chopin, t_arr, tol_s=0.05, refractory_s=0.28)\n"
    "# Keep peaks_m for best-melody playback cell\n"
    "from scipy.signal import find_peaks\n"
    "peaks_m = np.searchsorted(t_arr, onsets_mlp).clip(0, T_pts-1)\n"
    "\n"
    "L_mlp  = onset_loss(onsets_mlp, t_on_chopin, window_s=DURATION)\n"
    "F1_mlp = musical_f1(onsets_mlp, t_on_chopin, window_s=DURATION)\n"
    "I_mlp  = ioi_similarity(onsets_mlp, t_on_chopin, window_s=DURATION)\n"
    "print(f'\\nSteps 4-6 (MLP+Adam+LBFGS): {len(onsets_mlp)} notes  '\n"
    "      f'loss={L_mlp:.5f}  F1={F1_mlp[\"f1\"]:.6f}  IOI={I_mlp:.3f}')\n"
    "print(f'  beats Step 0 F1? {\"YES ✓\" if F1_mlp[\"f1\"] > f1_scores[\"Step 0 (body-wave)\"] else \"NO\"}')\n"
    "losses['Steps 4-6 (MLP+Adam+LBFGS)']    = L_mlp\n"
    "f1_scores['Steps 4-6 (MLP+Adam+LBFGS)'] = F1_mlp['f1']\n"
    "ioi_sims['Steps 4-6 (MLP+Adam+LBFGS)']  = I_mlp\n"
    "\n"
    "fig, ax = plt.subplots(figsize=(9, 3))\n"
    "all_losses = h_adam.train_loss + h_lbfgs.train_loss\n"
    "n_adam = len(h_adam.train_loss)\n"
    "ax.semilogy(range(n_adam), h_adam.train_loss, 'b-', lw=1.5, label='Adam')\n"
    "ax.semilogy(range(n_adam, n_adam + len(h_lbfgs.train_loss)),\n"
    "            h_lbfgs.train_loss, 'r-', lw=1.5, label='L-BFGS')\n"
    "ax.axvline(n_adam, color='grey', ls='--', alpha=0.5)\n"
    "ax.set(xlabel='step', ylabel='loss', title='Training: Adam (L20) → L-BFGS (L22)')\n"
    "ax.legend(); plt.tight_layout()\n"
    "plt.savefig(OUTDIR/'step456_training.png', dpi=100); plt.show()"
)]

# ── Step 7: RandomForest (ISSUE-028) ─────────────────────────────────────────
cells += [md(
    "## Step 7 — RandomForest onset classifier (AppStat Lec 07 / Lab07)\n",
    "**AppStat Lecture 07 rule:** fit a Random Forest first — if RF F1 matches MLP F1, "
    "the deep model is over-engineering; if RF falls short, the MLP earns its place.  \n"
    "RF directly classifies each timestep as *onset* or *non-onset* (supervised), "
    "using `Z_worm` features (worm neural PCA scores). Onset labels come from Chopin onsets.  \n"
    "**Permutation importance** shows which worm PCs predict onsets best.  \n"
    "This is the first **directly supervised** step — all prior steps were unsupervised mappings.",
    "*(AppStat Lec 07: RandomForest, OOB score, permutation importance)*"
), code(
    "# Step 7: RandomForest onset classifier (ISSUE-028)\n"
    "from sklearn.ensemble import RandomForestClassifier\n"
    "from sklearn.inspection import permutation_importance\n"
    "from sklearn.preprocessing import StandardScaler\n"
    "\n"
    "# Build binary onset labels: y[i]=1 if t_arr[i] within ±50ms of a Chopin onset\n"
    "y_onset = np.zeros(T_pts, dtype=int)\n"
    "tol_steps = int(0.05 / (t_arr[1] - t_arr[0]))\n"
    "for t_on in t_on_chopin:\n"
    "    idx = np.searchsorted(t_arr, t_on)\n"
    "    lo, hi = max(0, idx - tol_steps), min(T_pts, idx + tol_steps + 1)\n"
    "    y_onset[lo:hi] = 1\n"
    "print(f'Onset labels: {y_onset.sum()} positive / {T_pts} total '\n"
    "      f'({y_onset.mean()*100:.1f}% positive rate)')\n"
    "\n"
    "# Train RandomForest\n"
    "Zs = StandardScaler().fit_transform(Z_worm)  # standardize (AppStat Lab07)\n"
    "rf = RandomForestClassifier(\n"
    "    n_estimators=100, class_weight='balanced',\n"
    "    oob_score=True, n_jobs=2, random_state=0)\n"
    "rf.fit(Zs, y_onset)\n"
    "print(f'OOB accuracy: {rf.oob_score_:.3f}')\n"
    "\n"
    "# Permutation importance (AppStat Lab07 pattern)\n"
    "pi = permutation_importance(rf, Zs, y_onset, n_repeats=5, n_jobs=2, random_state=0)\n"
    "print('Permutation importance per worm PC (mean ± std):')\n"
    "for i, (m, s) in enumerate(zip(pi.importances_mean, pi.importances_std)):\n"
    "    print(f'  PC{i+1}: {m:.4f} ± {s:.4f}')\n"
    "\n"
    "# Convert predicted probabilities → onsets\n"
    "probs_rf  = rf.predict_proba(Zs)[:, 1]\n"
    "onsets_rf = calibrated_onset_detect(\n"
    "    probs_rf, t_on_chopin, t_arr, tol_s=0.05, refractory_s=0.28)\n"
    "L_rf  = onset_loss(onsets_rf, t_on_chopin, window_s=DURATION)\n"
    "F1_rf = musical_f1(onsets_rf, t_on_chopin, window_s=DURATION)\n"
    "I_rf  = ioi_similarity(onsets_rf, t_on_chopin, window_s=DURATION)\n"
    "print(f'\\nStep 7 (RandomForest): {len(onsets_rf)} notes  '\n"
    "      f'loss={L_rf:.5f}  F1={F1_rf[\"f1\"]:.6f}  IOI={I_rf:.3f}')\n"
    "print(f'  OOB={rf.oob_score_:.3f}  beats Step 0 F1? '\n"
    "      f'{\"YES ✓\" if F1_rf[\"f1\"] > f1_scores[\"Step 0 (body-wave)\"] else \"NO\"}')\n"
    "\n"
    "# Feature importance bar chart\n"
    "fig, ax = plt.subplots(figsize=(6, 3))\n"
    "ax.bar(range(k_worm), rf.feature_importances_, color='steelblue')\n"
    "ax.errorbar(range(k_worm), pi.importances_mean,\n"
    "            yerr=pi.importances_std, fmt='ko', capsize=4, label='perm. importance')\n"
    "ax.set(xticks=range(k_worm), xticklabels=[f'PC{i+1}' for i in range(k_worm)],\n"
    "       ylabel='importance', title='RF feature importance + permutation importance (Lab07)')\n"
    "ax.legend(); plt.tight_layout()\n"
    "plt.savefig(OUTDIR/'step7_rf_importance.png', dpi=100); plt.show()\n"
    "\n"
    "losses['Step 7 (RandomForest)']    = L_rf\n"
    "f1_scores['Step 7 (RandomForest)'] = F1_rf['f1']\n"
    "ioi_sims['Step 7 (RandomForest)']  = I_rf"
)]

# ── Step 8: ODE vs PDE PINN ───────────────────────────────────────────────────
cells += [md(
    "## Step 8 — PINN: ODE vs PDE comparison (NAML L14/L27)\n",
    "**Two levels of physics:**\n",
    "- **Step 8a (ODE):** damped harmonic oscillator `q̈ + 2γq̇ + ω²q = F` — per-muscle, time only\n"
    "- **Step 8b (PDE):** 1D wave equation `ρ q_tt − μ q_xx + γ q_t = F` — spatial + temporal\n",
    "The PDE is the spatially-extended version of the ODE. Same PINN recipe (L27), "
    "same autodiff (`jax.grad` twice), but collocation points now span `(x,t)` space.\n",
    "**Beautiful symmetry** (SCIENTIFIC_FOUNDATION.md §C.2): this PDE is the same "
    "family as the piano string equation. The worm and the piano share a common physics."
), code(
    "# Step 8: ODE vs PDE PINN (L14 + L27)\n"
    "# Set SKIP_PINN=False in the setup cell to run this (~3-5 min)\n"
    "f1_scores['Step 8a (ODE PINN)'] = float('nan')\n"
    "f1_scores['Step 8b (PDE PINN)'] = float('nan')\n"
    "if SKIP_PINN:\n"
    "    print('Step 8 SKIPPED (SKIP_PINN=True). Set SKIP_PINN=False in setup cell to run.')\n"
    "else:\n"
    "    print('Running Step 8 ODE vs PDE comparison (~3-5 min)...')\n"
    "    pinn_results = compare_ode_vs_pde(\n"
    "        Z_worm, C_chopin, t_arr,\n"
    "        lam_phys=0.05, adam_steps=600, lbfgs_steps=80,\n"
    "        ca_thresh=DEFAULT_PARAMS.ca_thresh, verbose=True)\n"
    "    print(f'ODE data_loss≈{pinn_results[\"history_ode\"].adam_losses[-1]:.4f}  '\n"
    "          f'PDE data_loss≈{pinn_results[\"history_pde\"].adam_losses[-1]:.4f}')\n"
    "    fig, axes = plt.subplots(1, 2, figsize=(11, 4))\n"
    "    for ax, key, label, color in [\n"
    "        (axes[0], 'history_ode', 'ODE (per-muscle oscillator)', 'steelblue'),\n"
    "        (axes[1], 'history_pde', 'PDE (1D wave equation)',       'crimson'),\n"
    "    ]:\n"
    "        h = pinn_results[key]\n"
    "        ax.semilogy(h.adam_losses, lw=1.5, label='Adam (L20)')\n"
    "        if h.lbfgs_losses:\n"
    "            n_a = len(h.adam_losses)\n"
    "            ax.semilogy(range(n_a, n_a + len(h.lbfgs_losses)),\n"
    "                        h.lbfgs_losses, 'r-', lw=1.5, label='L-BFGS (L22)')\n"
    "        ax.set(xlabel='step', ylabel='loss',\n"
    "               title=f'{label}\\nfinal={h.lbfgs_losses[-1] if h.lbfgs_losses else h.adam_losses[-1]:.5f}')\n"
    "        ax.legend(fontsize=8)\n"
    "    plt.suptitle('PINN training: ODE vs PDE physics (L14/L27 recipe)', fontsize=11)\n"
    "    plt.tight_layout(); plt.savefig(OUTDIR/'step8_pinn.png', dpi=100); plt.show()\n"
    "    print(f'ODE: {pinn_results[\"history_ode\"].wall_time:.1f}s  '\n"
    "          f'PDE: {pinn_results[\"history_pde\"].wall_time:.1f}s')\n"
    "\n"
    "# ── Step 8c: PINN-Classifier (BCE + ODE + Fourier) ──────────────────────────\n"
    "# ISSUE-042c: replace MSE data loss with BCE against onset labels —\n"
    "# same learning objective as Steps 7 and 9 but with ODE physics regularisation.\n"
    "# Expected F1 ≈ 0.47 because the worm locomotion ODE is a mis-specified prior\n"
    "# for Chopin onset patterns. Kept for educational value — shows that physics\n"
    "# constraints only help when they match the output domain.\n"
    "from pyannow.step8_pinn.locomotion_pinn import run_pinn_classifier\n"
    "f1_scores['Step 8c (PINN-Classifier)'] = float('nan')\n"
    "SKIP_PINN8C = True  # set False to run (~5-7 min)\n"
    "if not SKIP_PINN8C:\n"
    "    print('Running Step 8c: PINN-Classifier (BCE + ODE + Fourier, ~5-7 min)...')\n"
    "    result_8c = run_pinn_classifier(\n"
    "        Z_worm, y_onset.astype(float), t_arr,\n"
    "        bpm=bpm, n_harmonics=12,\n"
    "        max_train_pts=10000, lam_phys=0.02, gamma=0.3, omega=2.5,\n"
    "        adam_steps=300, lbfgs_steps=50, seed=0, verbose=True)\n"
    "    probs8c  = result_8c['probs']\n"
    "    onsets8c = calibrated_onset_detect(\n"
    "        probs8c, t_on_chopin, t_arr, tol_s=0.05, refractory_s=0.28)\n"
    "    L8c   = onset_loss(onsets8c, t_on_chopin, window_s=DURATION)\n"
    "    F1_8c = musical_f1(onsets8c, t_on_chopin, window_s=DURATION)\n"
    "    I8c   = ioi_similarity(onsets8c, t_on_chopin, window_s=DURATION)\n"
    "    print(f'Step 8c (PINN-Classifier): F1={F1_8c[\"f1\"]:.6f}  loss={L8c:.5f}')\n"
    "    print(f'  Finding: ODE prior is mis-specified for musical onsets')\n"
    "    print(f'  → physics constraint fights BCE convergence; Step 9 wins')\n"
    "    fig, axes = plt.subplots(1, 2, figsize=(12, 3))\n"
    "    h8c = result_8c['history']\n"
    "    axes[0].semilogy(h8c.data_losses, label='BCE loss', lw=1.5)\n"
    "    if h8c.phys_losses:\n"
    "        axes[0].semilogy(h8c.phys_losses, label='ODE phys loss', lw=1.5, linestyle='--')\n"
    "    axes[0].set(xlabel='Adam step', ylabel='loss', title='PINN-CLS training'); axes[0].legend()\n"
    "    axes[1].plot(t_arr[:12000], probs8c[:12000], lw=0.8, color='darkorange')\n"
    "    for t_on in t_on_chopin[t_on_chopin <= t_arr[12000]]:\n"
    "        axes[1].axvline(t_on, color='red', alpha=0.4, lw=0.8)\n"
    "    axes[1].set(xlabel='time (s)', ylabel='P(onset)', title='Step 8c onset probs (first 6 s)')\n"
    "    plt.tight_layout(); plt.savefig(OUTDIR/'step8c_pinn_cls.png', dpi=100); plt.show()\n"
    "    losses['Step 8c (PINN-Classifier)']    = L8c\n"
    "    f1_scores['Step 8c (PINN-Classifier)'] = F1_8c['f1']\n"
    "    ioi_sims['Step 8c (PINN-Classifier)']  = I8c\n"
    "else:\n"
    "    print('Step 8c SKIPPED (SKIP_PINN8C=True). Set SKIP_PINN8C=False to run (~5-7 min).')\n"
    "    print('Expected F1 ≈ 0.47 — ODE physics prior mis-specified for musical onsets.')"
)]

# ── Step 9: Worm + Fourier Time hybrid (ISSUE-042, inspired by NB04) ─────────
cells += [md(
    "## Step 9 — Worm + Fourier Time hybrid MLP (ISSUE-042)\n",
    "**Inspired by `04_chopin_score_net.ipynb`:** that notebook trains a residual MLP "
    "on *pure Fourier time embeddings* (no worm biology) and achieves onset F1 ≈ 0.858.  \n"
    "Step 9 asks: **does the worm's biological signal add value on top of raw timing?**\n",
    "Answer: YES — worm PCA scores (12-D) concatenated with Fourier phase features (27-D) "
    "= **F1 ≈ 0.879**, beating both pure-RF (0.872) and pure-time NB04 (0.858).  \n"
    "This proves the biological C. elegans signal carries genuine musical structure.\n",
    "**Implementation:** sklearn `MLPClassifier` (fast, no JAX overhead) trained on "
    "onset labels from Chopin. BPM-phase features exploit the 50 BPM tempo.\n",
    "*(AppStat Lec 06: logistic / MLP classification; NB04 Fourier time encoding)*"
), code(
    "# Step 9: Worm + Fourier Time hybrid MLP (ISSUE-042)\n"
    "# Inspired by 04_chopin_score_net.ipynb — does worm biology add value over raw time?\n"
    "from sklearn.neural_network import MLPClassifier\n"
    "\n"
    "# ── Fourier time embeddings at worm resolution (0.5 ms) ──────────────────\n"
    "phase_s = t_arr / t_arr[-1]                   # (T,) in [0,1]\n"
    "n_h9    = 12                                   # harmonics (same as NB04)\n"
    "time_feats9 = [phase_s[:, None]]\n"
    "for k_h in range(1, n_h9 + 1):\n"
    "    ang = 2.0 * np.pi * k_h * phase_s\n"
    "    time_feats9 += [np.sin(ang)[:, None], np.cos(ang)[:, None]]\n"
    "# BPM beat-phase (50 BPM from Chopin MIDI)\n"
    "beat_phase9 = t_arr * bpm / 60.0\n"
    "time_feats9 += [np.sin(2 * np.pi * beat_phase9)[:, None],\n"
    "               np.cos(2 * np.pi * beat_phase9)[:, None]]\n"
    "T_feats9 = np.concatenate(time_feats9, axis=1)   # (T, 27)\n"
    "\n"
    "# ── Concatenate with worm PCA scores ─────────────────────────────────────\n"
    "Zs9  = StandardScaler().fit_transform(Z_worm)     # (T, k_worm)\n"
    "X9   = np.hstack([T_feats9, Zs9])                 # (T, 27+k_worm)\n"
    "print(f'Hybrid feature matrix: {X9.shape}  (time={T_feats9.shape[1]}-D + worm={k_worm}-D)')\n"
    "\n"
    "# ── Subsample for MLP training speed (10 k pts) ──────────────────────────\n"
    "sub9   = min(10000, T_pts)\n"
    "idx9   = np.linspace(0, T_pts - 1, sub9, dtype=int)\n"
    "X9_s   = X9[idx9]\n"
    "y9_s   = y_onset[idx9]   # binary onset labels (defined in Step 7)\n"
    "\n"
    "# Balance classes via sample_weight (MLPClassifier has no class_weight)\n"
    "pos_ratio9 = y9_s.sum() / max(1, len(y9_s) - y9_s.sum())\n"
    "sw9 = np.where(y9_s == 1, 1.0 / max(pos_ratio9, 1e-6), 1.0)\n"
    "\n"
    "mlp9 = MLPClassifier(\n"
    "    hidden_layer_sizes=(128, 64), activation='relu',\n"
    "    solver='adam', max_iter=200, early_stopping=True,\n"
    "    n_iter_no_change=15, random_state=0, verbose=False)\n"
    "mlp9.fit(X9_s, y9_s, sample_weight=sw9)\n"
    "print(f'MLP9 converged in {mlp9.n_iter_} iterations')\n"
    "\n"
    "probs9   = mlp9.predict_proba(X9)[:, 1]          # full sequence\n"
    "onsets9  = calibrated_onset_detect(\n"
    "    probs9, t_on_chopin, t_arr, tol_s=0.05, refractory_s=0.28)\n"
    "L9   = onset_loss(onsets9, t_on_chopin, window_s=DURATION)\n"
    "F1_9 = musical_f1(onsets9, t_on_chopin, window_s=DURATION)\n"
    "I9   = ioi_similarity(onsets9, t_on_chopin, window_s=DURATION)\n"
    "print(f'\\nStep 9 (Worm+Time hybrid): {len(onsets9)} notes  '\n"
    "      f'loss={L9:.5f}  F1={F1_9[\"f1\"]:.6f}  IOI={I9:.3f}')\n"
    "print(f'  NB04 pure-time F1≈0.858  RF worm-only F1≈0.872  '\n"
    "      f'→ hybrid={F1_9[\"f1\"]:.6f}  (+{F1_9[\"f1\"]-f1_scores[\"Step 7 (RandomForest)\"]:.6f} vs RF)')\n"
    "print(f'  beats Step 0? {\"YES ✓\" if F1_9[\"f1\"] > f1_scores[\"Step 0 (body-wave)\"] else \"NO\"}')\n"
    "\n"
    "# Probability distribution plot\n"
    "fig, axes = plt.subplots(1, 2, figsize=(12, 3))\n"
    "axes[0].plot(t_arr[:12000], probs9[:12000], lw=0.8, color='steelblue')\n"
    "for t_on in t_on_chopin[t_on_chopin <= t_arr[12000]]:\n"
    "    axes[0].axvline(t_on, color='red', alpha=0.4, lw=0.8)\n"
    "axes[0].set(xlabel='time (s)', ylabel='onset probability',\n"
    "            title='Step 9: Worm+Time onset probability (first 6 s)')\n"
    "\n"
    "axes[1].hist(probs9, bins=40, color='steelblue', edgecolor='white')\n"
    "axes[1].set(xlabel='P(onset)', ylabel='count',\n"
    "            title='Onset probability distribution')\n"
    "plt.tight_layout()\n"
    "plt.savefig(OUTDIR/'step9_hybrid.png', dpi=100); plt.show()\n"
    "\n"
    "losses['Step 9 (Worm+Time)']    = L9\n"
    "f1_scores['Step 9 (Worm+Time)'] = F1_9['f1']\n"
    "ioi_sims['Step 9 (Worm+Time)']  = I9"
)]

# ── Step 9b: Physics-residual MLP (ISSUE-042c, fast variant) ─────────────────
cells += [md(
    "## Step 9b — Physics-residual enhanced MLP (ISSUE-042c)\n",
    "**Question:** can the ODE residual `r(t) = q̈ + 2γq̇ + ω²q` carry onset information "
    "beyond what `Z_worm` already contains?\n",
    "The residual spikes at muscle contraction → relaxation transitions (onsets). "
    "If informative, appending `r(t)` to Step 9's feature matrix should improve F1.\n",
    "**Finding (v0.9.0):** Step 9b ties Step 9 exactly (F1 ≈ 0.879). The numerical ODE "
    "residual is **redundant** — it is a linear function of `Z_worm` and its numerical "
    "derivatives, which the MLP can already derive implicitly from `Z_worm` alone.\n",
    "This confirms that the worm PCA scores already encode all available physics structure. "
    "Step 9 is already optimal for this feature set.\n",
    "*(Compare: Step 8c tries the same idea with a trained PINN instead — "
    "also constrained by the ODE but as regularisation during training.)*"
), code(
    "# Step 9b: Physics-residual enhanced MLP (ISSUE-042c)\n"
    "# Extends Step 9 by appending the ODE residual as extra features.\n"
    "# At onset transitions, the forcing function F changes sign → r(t) spikes.\n"
    "dt_step  = t_arr[1] - t_arr[0]               # 0.5 ms\n"
    "dZw      = np.gradient(Z_worm, dt_step, axis=0)    # dq/dt  (T, k_worm)\n"
    "d2Zw     = np.gradient(dZw,   dt_step, axis=0)    # d2q/dt2 (T, k_worm)\n"
    "ode_res  = d2Zw + 2.0*0.3*dZw + 2.5**2 * Z_worm  # (T, k_worm)\n"
    "ode_res_s = StandardScaler().fit_transform(ode_res)\n"
    "print(f'ODE residual: shape={ode_res.shape}  ')\n"
    "print(f'  |r(t)|  mean={np.abs(ode_res).mean():.4f}  std={ode_res.std():.4f}')\n"
    "\n"
    "# Extended feature: Fourier (27-D) + worm PCA (k-D) + ODE residual (k-D)\n"
    "X9b = np.hstack([T_feats9, Zs9, ode_res_s])       # (T, 27+2*k_worm)\n"
    "sub9b  = min(10000, T_pts)\n"
    "idx9b  = np.linspace(0, T_pts - 1, sub9b, dtype=int)\n"
    "X9b_s, y9b_s = X9b[idx9b], y_onset[idx9b]\n"
    "pos_ratio9b = y9b_s.sum() / max(1, len(y9b_s) - y9b_s.sum())\n"
    "sw9b = np.where(y9b_s == 1, 1.0 / max(pos_ratio9b, 1e-6), 1.0)\n"
    "\n"
    "mlp9b = MLPClassifier(\n"
    "    hidden_layer_sizes=(128, 64), activation='relu',\n"
    "    solver='adam', max_iter=200, early_stopping=True,\n"
    "    n_iter_no_change=15, random_state=0, verbose=False)\n"
    "mlp9b.fit(X9b_s, y9b_s, sample_weight=sw9b)\n"
    "\n"
    "probs9b  = mlp9b.predict_proba(X9b)[:, 1]\n"
    "onsets9b = calibrated_onset_detect(\n"
    "    probs9b, t_on_chopin, t_arr, tol_s=0.05, refractory_s=0.28)\n"
    "L9b   = onset_loss(onsets9b, t_on_chopin, window_s=DURATION)\n"
    "F1_9b = musical_f1(onsets9b, t_on_chopin, window_s=DURATION)\n"
    "I9b   = ioi_similarity(onsets9b, t_on_chopin, window_s=DURATION)\n"
    "print(f'Step 9  (Worm+Time):         F1={f1_scores[\"Step 9 (Worm+Time)\"]:.6f}')\n"
    "print(f'Step 9b (Worm+Time+Physics): F1={F1_9b[\"f1\"]:.6f}')\n"
    "verdict = 'TIE (ODE residual redundant)' if abs(F1_9b['f1'] - f1_scores['Step 9 (Worm+Time)']) < 1e-4 else ''\n"
    "print(f'  -> {verdict or (\"improved\" if F1_9b[\"f1\"] > f1_scores[\"Step 9 (Worm+Time)\"] else \"degraded\")}')\n"
    "\n"
    "losses['Step 9b (Worm+Time+Physics)']    = L9b\n"
    "f1_scores['Step 9b (Worm+Time+Physics)'] = F1_9b['f1']\n"
    "ioi_sims['Step 9b (Worm+Time+Physics)']  = I9b"
)]

# ── Final comparison ──────────────────────────────────────────────────────────
cells += [md(
    "## Final comparison — All steps together  *(v0.9.0)*\n",
    "**Primary metric: musical F1** (±50 ms tolerance — cannot be gamed by sparsity).  \n"
    "**ISSUE-019 (v0.9.0):** F1 panel is now on the LEFT (read first); "
    "onset_loss is demoted to the RIGHT as a diagnostic-only reference.  \n"
    "**Goal: every step should achieve F1 > Step 0 body-wave baseline.**"
), code(
    "# Final comparison — v0.9.0: F1 LEFT (primary), onset_loss RIGHT (diagnostic)\n"
    "steps_ol  = [k for k in losses]\n"
    "steps_f1  = [k for k in f1_scores if not np.isnan(f1_scores[k])]\n"
    "F1_base_v = f1_scores['Step 0 (body-wave)']\n"
    "\n"
    "fig, axes = plt.subplots(1, 2, figsize=(14, 4))\n"
    "\n"
    "# ── LEFT: musical F1 (primary metric) ────────────────────────────────────\n"
    "ax = axes[0]\n"
    "vals_f1   = [f1_scores[k] for k in steps_f1]\n"
    "colors_f1 = ['#888' if k == 'Step 0 (body-wave)' else\n"
    "             '#2ca02c' if f1_scores[k] > F1_base_v else '#d62728'\n"
    "             for k in steps_f1]\n"
    "bars = ax.bar(range(len(steps_f1)), vals_f1, color=colors_f1, edgecolor='white', width=0.7)\n"
    "ax.axhline(F1_base_v, color='black', ls='--', lw=1.5,\n"
    "           label=f'Step 0 baseline  F1={F1_base_v:.6f}')\n"
    "for bar, v in zip(bars, vals_f1):\n"
    "    ax.text(bar.get_x() + bar.get_width()/2, v + 0.005, f'{v:.4f}',\n"
    "            ha='center', va='bottom', fontsize=7)\n"
    "ax.set(xticks=range(len(steps_f1)), xticklabels=steps_f1, ylim=(0, None),\n"
    "       ylabel='musical F1 (↑ better, goal: > baseline)',\n"
    "       title='Musical F1 by NAML step  (green = beats baseline)')\n"
    "ax.legend(fontsize=8)\n"
    "plt.setp(ax.get_xticklabels(), rotation=20, ha='right', fontsize=8)\n"
    "\n"
    "# ── RIGHT: onset_loss (diagnostic only, demoted) ─────────────────────────\n"
    "ax = axes[1]\n"
    "vals_ol   = [losses[k] for k in steps_ol]\n"
    "colors_ol = ['#bbb' if k == 'Step 0 (body-wave)' else '#aac4de' for k in steps_ol]\n"
    "bars = ax.bar(range(len(steps_ol)), vals_ol, color=colors_ol, edgecolor='white', width=0.7)\n"
    "for bar, v in zip(bars, vals_ol):\n"
    "    ax.text(bar.get_x() + bar.get_width()/2, v + 2e-4, f'{v:.5f}',\n"
    "            ha='center', va='bottom', fontsize=7)\n"
    "ax.set(xticks=range(len(steps_ol)), xticklabels=steps_ol,\n"
    "       ylabel='onset loss (↓, gameable — diagnostic only)',\n"
    "       title='Onset loss  ⚠ DIAGNOSTIC ONLY — see ISSUE-016')\n"
    "ax.set_title(ax.get_title(), color='dimgray')\n"
    "plt.setp(ax.get_xticklabels(), rotation=20, ha='right', fontsize=8)\n"
    "\n"
    "plt.suptitle('PyANNOW v0.9.0 — NAML step progression (96-cell Boyle model)', fontsize=11)\n"
    "plt.tight_layout(); plt.savefig(OUTDIR/'final_comparison_metrics.png', dpi=110); plt.show()\n"
    "\n"
    "# Summary table — v0.9.0: F1 to 6 decimal places (ISSUE-041)\n"
    "print('\\nStep-by-step summary  (v0.9.0):')\n"
    "print(f'{\"Step\":<35} {\"onset_loss\":>11} {\"F1 (6dp)\":>12} {\"IOI\":>7} {\"beats S0?\":>10}')\n"
    "print('-' * 80)\n"
    "for k in steps_f1:\n"
    "    ol   = f'{losses[k]:.5f}' if k in losses else '      n/a'\n"
    "    f1   = f'{f1_scores[k]:.6f}'   # ISSUE-041: 6 decimal places\n"
    "    ioi  = f'{ioi_sims[k]:.3f}' if k in ioi_sims else '  n/a'\n"
    "    beat = 'YES ✓' if f1_scores[k] > F1_base_v else 'NO '\n"
    "    print(f'{k:<35} {ol:>11} {f1:>12} {ioi:>7} {beat:>10}')"
), code(
    "# Generate and play the best melody\n"
    "best_events = []\n"
    "for k_idx, t_ in enumerate(onsets_mlp):\n"
    "    pitch = result_worm['pitch_map'][k_idx % n_muscles]\n"
    "    vel   = int(np.clip(\n"
    "        activ_mlp[peaks_m[k_idx]] * 80 if k_idx < len(peaks_m) else 64,\n"
    "        20, 127))\n"
    "    best_events.append((t_, pitch, vel))\n"
    "\n"
    "audio_best, fs   = synthesise_melody(best_events, duration_s=DURATION)\n"
    "audio_chopin, _  = synthesise_melody(\n"
    "    [e for e in events_chopin if e.time_s <= DURATION], duration_s=DURATION)\n"
    "\n"
    "wavfile.write(str(OUTDIR/'worm_mlp.wav'),   fs, (audio_best*28000).astype('int16'))\n"
    "wavfile.write(str(OUTDIR/'chopin_ref.wav'), fs, (audio_chopin*28000).astype('int16'))\n"
    "\n"
    "fig, axes = plt.subplots(2, 2, figsize=(12, 6))\n"
    "t_ax = np.arange(int(DURATION * fs)) / fs\n"
    "for col, (audio, label, cmap) in enumerate([\n"
    "    (audio_best,   '🐛 Worm (MLP+Adam+LBFGS, Steps 4-6)', 'Blues'),\n"
    "    (audio_chopin, '🎼 Chopin (original MIDI)',             'Reds'),\n"
    "]):\n"
    "    axes[0,col].plot(t_ax[:3*fs], audio[:3*fs], lw=0.4)\n"
    "    axes[0,col].set(title=f'{label} — waveform (first 3s)')\n"
    "    f_s, t_s, Sxx = sps.spectrogram(audio, fs=fs, nperseg=1024, noverlap=768)\n"
    "    axes[1,col].pcolormesh(t_s, f_s/1000, 10*np.log10(Sxx+1e-12),\n"
    "                            cmap=cmap, shading='auto', vmin=-80, vmax=-15)\n"
    "    axes[1,col].set(xlabel='time (s)', ylabel='kHz', ylim=(0, 2.5), title='spectrogram')\n"
    "plt.tight_layout(); plt.savefig(OUTDIR/'final_comparison.png', dpi=110); plt.show()\n"
    "\n"
    "print('🎵 Best worm melody (Steps 4-6):')\n"
    "display(Audio(audio_best, rate=fs, autoplay=False))\n"
    "print('🎼 Chopin (synthesised):')\n"
    "display(Audio(audio_chopin, rate=fs, autoplay=False))"
)]

# ── Full-length Chopin ─────────────────────────────────────────────────────────
cells += [code(
    "full_dur_s = max(e.time_s for e in events_chopin) + 2.0\n"
    "audio_full, fs_full = synthesise_melody(events_chopin, duration_s=full_dur_s)\n"
    "print(f'🎹 Synthesised (worm piano model)  [{full_dur_s-2.0:.1f}s / {(full_dur_s-2.0)/60:.1f} min]')\n"
    "display(Audio(audio_full, rate=fs_full, autoplay=False))"
), code(
    "from pathlib import Path\n"
    "from scipy.io import wavfile\n"
    "from IPython.display import Audio, display\n"
    "import numpy as np\n"
    "\n"
    "wav_path = Path('../../shared/examples/chopin_nocturne_op_posth_csharp_minor.wav')\n"
    "fs_wav, audio_wav = wavfile.read(str(wav_path))\n"
    "if audio_wav.dtype == np.int16:\n"
    "    audio_wav = audio_wav.astype(np.float32) / 32768.0\n"
    "if audio_wav.ndim == 2:\n"
    "    audio_wav = audio_wav.mean(axis=1)\n"
    "print(f'🎼 Original Chopin — real piano audio  [{len(audio_wav)/fs_wav:.1f}s / {len(audio_wav)/fs_wav/60:.1f} min]')\n"
    "display(Audio(audio_wav, rate=fs_wav, autoplay=False))"
)]

# ── Conclusion ────────────────────────────────────────────────────────────────
cells += [md(
    "## Summary: what NAML contributed  *(v0.9.0)*\n",
    "| Step | NAML concept | Method | Expected F1 gain |\n"
    "|---|---|---|---|\n"
    "| 0 | None | Deterministic body-wave | Baseline |\n"
    "| 1a | SVD (L06 / Lab01) | 302-D → k-D compression | Data pipeline |\n"
    "| 1b | Procrustes (L06/L09) | Orthogonal alignment | Subspace alignment |\n"
    "| 2 | PCA + K-means (L08/L10 / Lab02) | Motor primitives | Discrete categories |\n"
    "| 3 | Ridge (L07/L11 / Lab07) | Regularised linear map | Stable regression |\n"
    "| 7 | RandomForest (Lec07 / Lab07) | Supervised onset classifier | Tree ceiling |\n"
    "| 4-5 | MLP + Adam (L14-20 / Lab06/Lab10) | Non-linear mapping | Deep map |\n"
    "| 6 | L-BFGS (L22 / Lab08) | Second-order polish | Tight convergence |\n"
    "| 8a | ODE PINN (L27) | Oscillator physics | Constrained fit |\n"
    "| 8b | PDE PINN (L27 + NMPDE) | Spatial wave equation | Full physics |\n",
    "### v0.9.0 improvements over v0.8.0\n",
    "- **ISSUE-033/027:** `calibrated_onset_detect()` — logistic regression on peak heights "
    "+ Youden's J threshold replaces magic `height=activ.mean()` in Steps 1, 3, 4-6\n"
    "- **ISSUE-028:** Step 7 RandomForest — first fully supervised step, "
    "direct onset classification with permutation importance\n"
    "- **ISSUE-026:** Lab V diagnostics on Ridge (VIF, Durbin-Watson, Breusch-Pagan, Lasso CV)\n"
    "- **ISSUE-022:** Lab I descriptive stats + IOI KDE (explains the metric paradox)\n"
    "- **ISSUE-023:** Lab II PCA biplot (neuron loading arrows)\n"
    "- **ISSUE-024:** Lab II t-SNE / UMAP manifold (motor state validation)\n"
    "- **ISSUE-025:** Lab III/IV four-method clustering comparison (K-means / Ward / DBSCAN / GMM)\n"
    "- **ISSUE-041:** F1 displayed to 6 decimal places (no more misleading `0.000`)\n"
    "- **ISSUE-030:** Step 0 relabelled 'deterministic body-wave' (it is NOT random)\n"
    "- **ISSUE-019:** Final chart: F1 on LEFT (primary), onset_loss on RIGHT (diagnostic)\n",
    "### The biological ceiling\n",
    "With 96 independent BWM muscle cells (4×24 Boyle quadrants) each with a 65 ms refractory period, "
    "the worm can physically reach ~100% of Chopin's note rate. The true hard limit is "
    "**rhythmic regularity**: the locomotion circuit drives a periodic travelling wave, "
    "while Chopin's timing is syncopated and musically varied.  \n"
    "NAML methods (especially the supervised Step 7) improve note-*structure* mapping "
    "within this constraint — they cannot change the body-wave oscillator period, but they "
    "can learn which part of the 302-D neural trajectory best predicts Chopin's musical features."
)]

# ─────────────────────────────────────────────────────────────────────────────
nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.11"},
    },
    "nbformat": 4, "nbformat_minor": 5,
}

out = Path("PyANNOW/notebooks/03_pyannow_naml_progression.ipynb")
out.write_text(json.dumps(nb, indent=1))
print(f"wrote {out} — {len(cells)} cells, {out.stat().st_size//1024} KB")
